name: Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  deploy:
    if: github.repository_owner != 'fastapi'
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Fix permissions
        run: |
          sudo rm -rf /home/meriemguesmi/actions-runner/_work/myapplication/myapplication/frontend/blob-report || true
          sudo rm -rf /home/meriemguesmi/actions-runner/_work/myapplication/myapplication/frontend/test-results || true
          sudo chown -R meriemguesmi:meriemguesmi /home/meriemguesmi/actions-runner/_work/myapplication/ || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat << EOF > .env
          DOMAIN=${{ secrets.DOMAIN_STAGING }}
          FRONTEND_HOST=${{ secrets.FRONTEND_HOST }}
          ENVIRONMENT=staging
          PROJECT_NAME=${{ secrets.PROJECT_NAME }}
          STACK_NAME=${{ secrets.STACK_NAME_STAGING }}
          BACKEND_CORS_ORIGINS=${{ secrets.BACKEND_CORS_ORIGINS }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          FIRST_SUPERUSER=${{ secrets.FIRST_SUPERUSER }}
          FIRST_SUPERUSER_PASSWORD=${{ secrets.FIRST_SUPERUSER_PASSWORD }}
          SMTP_HOST=${{ secrets.SMTP_HOST }}
          SMTP_USER=${{ secrets.SMTP_USER }}
          SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
          EMAILS_FROM_EMAIL=${{ secrets.EMAILS_FROM_EMAIL }}
          SMTP_TLS=${{ secrets.SMTP_TLS }}
          SMTP_SSL=${{ secrets.SMTP_SSL }}
          SMTP_PORT=${{ secrets.SMTP_PORT }}
          EMAIL=${{ secrets.EMAIL }}
          POSTGRES_SERVER=${{ secrets.POSTGRES_SERVER }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          DOCKER_IMAGE_BACKEND=${{ secrets.DOCKER_IMAGE_BACKEND }}
          DOCKER_IMAGE_FRONTEND=${{ secrets.DOCKER_IMAGE_FRONTEND }}
          GH_PAT=${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY=${{ secrets.GITHUB_REPOSITORY }}
          PROMETHEUS_URL=${{ secrets.PROMETHEUS_URL }}
          EOF

      - name: Create Traefik network
        run: docker network create traefik-public || true

      - name: Force clear DB port
        run: |
          CONTAINER_ID=$(docker ps -q --filter "publish=5432")
          if [ ! -z "$CONTAINER_ID" ]; then
            echo "Stopping container $CONTAINER_ID which is holding port 5432..."
            docker stop $CONTAINER_ID || true
          fi

      - name: Stop existing containers
        run: docker compose -f compose.yml -f compose.override.yml -p myapp-staging down || true

      - name: Remove old db volume
        run: docker volume rm myapp-staging_app-db-data || true

      - name: Build
        run: docker compose -f compose.yml -f compose.override.yml -p myapp-staging build

      - name: Deploy
        run: docker compose -f compose.yml -f compose.override.yml -p myapp-staging up -d