name: Smokeshow
on:
  workflow_run:
    workflows: [Test Backend]
    types: [completed]
jobs:
  smokeshow:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      actions: read
      statuses: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: coverage-html
          path: coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Display coverage
        run: cat coverage-report/coverage.txt || echo "Coverage report not found"
