name: SonarQube Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      #- name: Install dependencies
      #  working-directory: backend
      #  run: |
      #    pip install -r requirements.txt
      #    pip install pytest pytest-cov


      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync
        working-directory: backend

      - name: Run tests with coverage
        working-directory: backend
        run: |
          uv run pytest app/tests/ \
            --cov=app \
            --cov-report=xml:../coverage.xml \
            --cov-report=term-missing
        continue-on-error: true  

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

     # - name: SonarQube Quality Gate Check
     #   uses: SonarSource/sonarqube-quality-gate-action@master
     #  timeout-minutes: 5
     #   env:
     #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
     #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}