name: Test Backend
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d db mailcatcher
      - name: Migrate DB
        run: uv run bash scripts/prestart.sh
        working-directory: backend
      - name: Run tests
        run: uv run bash scripts/tests-start.sh "Coverage for ${{ github.sha }}"
        working-directory: backend
      - run: docker compose down -v --remove-orphans

      #adding security tests
      - name: Run SAST (Bandit)
        run: |
          pip install bandit
          bandit -r backend -ll -f json -o bandit-report.json || true
          bandit -r backend -ll || true

      - name: Dependency vulnerability scan (pip-audit)
        run: |
          pip install pip-audit
          pip-audit -f json -o pip-audit-report.json || true
          pip-audit || true

      - name: Secrets scan (Gitleaks)
        uses: gitleaks/gitleaks-action@v2

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.json
            pip-audit-report.json
          retention-days: 1

      - name: Store coverage files
        uses: actions/upload-artifact@v6
        with:
          name: coverage-html
          path: backend/htmlcov
          include-hidden-files: true

      - name: Coverage report
        run: uv run coverage report --fail-under=90
        working-directory: backend